### ISSUE TITLE
[Feature] Support Bookmark Separators in JSON definition 

### ISSUE THREAD

**Issue by chberger** [frederikb/bookmarksync#17]
With a large number of bookmarks, a bookmark list it can quickly become confusing. This is where (sub)-folders can help. However, sometimes a (sub-)folder is unwanted and a divider would be the desired way to go. 

It would be nice to define separators as child elements in the json bookmark definition file as well:

![image](https://github.com/frederikb/bookmarksync/assets/3606282/c9541fa4-deab-4b3b-b723-14f1f51c6694)

**Comment by frederikb** [comment]
Thanks for the idea, @chberger. Funnily enough I had the exact same thought yesterday.

Unfortunately there is one problem here: whereas Firefox supports the creation of vertical and horizontal separators, Chrome decided that this feature is [too complex for their users to understand.](https://bugs.chromium.org/p/chromium/issues/detail?id=7789)

That leaves us with a few options:

1. Don't support separators
2. Only support separators for Firefox and silenty drop them for Chrome
3. Substitute separators in Chrome with bookmarks with a name like "__________" to simulate a placeholder 
(inspired by https://bookmarkseparators.com/?i=folder )

What do you think? I'm not sure if I really like the UX of option 3 and forcing it on end users. On the other hand I wouldn't want to needlessly introduce a configuration toggle for this.

@mbechto @chberger

**Comment by mbechto** [comment]
Perhaps 3.

**Comment by chberger** [comment]
@frederikb Thanks for the explanation. I would vote for `option 2`. However, since I don't use Chrome at all `option 3` would also be acceptable. 😆

**Comment by mbechto** [comment]
> What do you think? I'm not sure if I really like the UX of option 3 and forcing it on end users. On the other hand I wouldn't want to needlessly introduce a configuration toggle for this.

@frederikb can't this be done in code? `if browser == 'chrome' { insert('________') } ...`

**Comment by frederikb** [comment]
@frederikb Yes. I simply meant that perhaps some Chrome users would rather forgoe separators entirely rather than having these substitutes.

Nevertheless, I'll give it a try and report back.

I'll also focus on horizontal separators only and skip vertical separators in the bookmarks (tool)bar.

**Comment by frederikb** [comment]
I've experimented with custom separators inspired by solutions such as https://bookmarkseparators.com/?i=folder . The overall verdict was that it's a bad UX and that we will skip separators for all non-Firefox browsers for now.
